run_name: tests_3          # "v_0", "v_1", …
category: junk
image_path: data/example_images/2.png
mask_path: data/example_images/mask3.png

hydra:
  run:
    dir: outputs/${sanitize:${image_path}}/${category}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${sanitize:${image_path}}/${category}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}


viz: true
sigma: 0.

seed: 42

defaults:
- flow_model: internal
- trainer: internal
- data: internal