
run_name: ${next_version:outputs}          # "v_0", "v_1", …

hydra:
  run:
    dir: outputs/${run_name}

  sweep:
    dir: outputs/${run_name}
    subdir: ${hydra.job.num}          # 0, 1, 2, …


image_path: data/example_images/2.png
mask_path: data/example_images/mask3.png
viz: true

seed: 42

defaults:
- flow_model: internal
- trainer: internal
- data: internal