flow_model:
  _target_: src.flows.flow.Flow

  # The path used during the flow; only AffinePath is supported
  path:
    _target_: src.flows.path.AffinePath 

    scheduler:
      _target_: src.flows.schedulers.CosineScheduler  # or CosineScheduler

  # The loss function used to train the model
  loss_fn:
    _target_: src.flows.losses.MSEFlowMatchingLoss

  # The model used to parameterize the flow
  model:
    _target_: src.experiments.models.models.TimeAndLabelConditionedMLP
    x_dim: 784
    output_dim: 784
    num_classes: 10
    y_emb_dim: 64
    num_fourier_bands: 6
    hidden_dim: 784
    n_layers: 5

  # The configuration for the flow
  cfg:
    _target_: src.flows.types.FlowConfig
    predicts: "x_1" # or "x_0", "score", "velocity", what the model predicts
    guidance: "CFG"  # or "classifier", "CFG"
    guidance_scale: 3.0
    guided_prob: 0.8
    compile: false # works only with nn.Module


  optimizer_cfg:
    _target_: torch.optim.Adam
    _partial_: true     # ← important!
    lr: 0.0003
    weight_decay: 0.0
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
