trainer:
  _target_: pytorch_lightning.Trainer

  max_epochs: 50
  log_every_n_steps: 10
  num_sanity_val_steps: 2
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: 1

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-step-{step}
      every_n_train_steps: 1000
      save_top_k: -1
      save_last: true

    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      every_n_epochs: 1
      save_top_k: -1
      save_last: false

    - _target_: experiments.callback.progress.ProgressLogger
      precision: 3

    - _target_: experiments.callback.tqdmbar.TQDMProgressBar

  logger:
    - _target_: pytorch_lightning.loggers.WandbLogger
      project: "StageTests"
      name: "toy_trainer"
      save_dir: "wandb/"
      log_model: false
