trainer:
  _target_: pytorch_lightning.Trainer

  max_epochs: 50
  log_every_n_steps: 1
  num_sanity_val_steps: 2
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: 1

  gradient_clip_val: 1.0
  detect_anomaly: true

  reload_dataloaders_every_n_epochs: 1

  deterministic: true

  callbacks:
    # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    #   filename: latest-{epoch}
    #   every_n_epochs: 1
    #   save_top_k: -1
    #   save_last: false

    - _target_: experiments.callback.progress.ProgressLogger
      precision: 3

    - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      refresh_rate: 1
      leave: true

    - _target_: experiments.callback.plot.GenerationPlotCallback
      num_samples: 16

  # logger:
  #   - _target_: pytorch_lightning.loggers.WandbLogger
  #     project: "StageTests"
  #     name: "v0"
  #     save_dir: "wandb/"
  #     log_model: false
