_target_: pytorch_lightning.Trainer

log_every_n_steps: 10
num_sanity_val_steps: 1
check_val_every_n_epoch: 1
accelerator: gpu
devices: 1

callbacks:

  - _target_: pytorch_lightning.callbacks.TQDMProgressBar
    refresh_rate: 1
    leave: true