defaults:
- base

_target_: src.internal_flow.flow.InpaintingFlow

ema_decay: 0.999975

# The model used to parameterize the flow
model:
  _target_: src.internal_flow.model.Model
  n_channels: 32
  output_dim: 3
  in_dim: 4 # 2*3 + 1
  skip: false
# The configuration for the flow

cfg:
  _target_: src.flows.types.FlowConfig
  predicts: velocity # or "x_0", "score", "velocity", what the model predicts
  guidance: none


pass_y: true
